### ISSUE TITLE
 Fails on lines beginning with -

### ISSUE THREAD

**Issue by joereynolds** [ozelentok/deoplete-gtags#1]
### Issue

Hi,

If you begin a line with the character '-', deoplete-gtags will bring an error:

```
[deoplete] [deoplete-gtags] Error: Invalid argumnets
global: invalid option -- ' '
```

(There's also a typo. argumnets should be arguments)

### To Reproduce

- Edit any file (new or existiing)
- Go into insert mode and type -
- Start typing some words after that
The error should appear

**Comment by ozelentok** [comment]
Hey,

I fixed the typo and the annoying error message

Thank you :+1:
